#!/usr/bin/env bash

set -e

sudo pacman -S stow --needed --noconfirm

if ! pacman -Q neovim &> /dev/null; then
    sudo pacman -S --noconfirm --needed neovim
fi

git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1

cd ~/dotfiles && stow nvim

if command -v luarocks &> /dev/null; then
    sudo luarocks install luacheck
fi
