#!/bin/bash

yay -S nmgui-bin --needed --noconfirm
yay -S chafa --needed --noconfirm
yay -S cbonsai --needed --noconfirm
yay -S evince --needed --noconfirm
yay -s localsend-bin --needed --noconfirm
yay -s kvnatum-manager --needed --noconfirm
sudo pacman -S gnome-clocks --needed --noconfirm
sudo pacman -S gnome-calender --needed --noconfirm
sudo pacman -S gnome-weather --needed --noconfirm
sudo pacman -S gnome-calculator --needed --noconfirm
sudo pacman -S blueberry --needed --noconfirm
sudo pacman -S yt-dlp --needed --noconfirm
sudo pacman -s python3 --needed --noconfirm
sudo pacman -s node --needed --noconfirm
sudo pacman -s docker --needed --noconfirm
sudo pacman -s wakatime --needed --noconfirm
sudo pacman -s figlet figlet-fonts --needed --noconfirm
sudo pacman -s zip --needed --noconfirm

## There are much more to put here
