customCommands:
  - key: ';'
    context: 'global'
    command: '/home/armaghan/.lazygit-commit.sh'
    output: terminal
    description: 'Quick add, commit, push'

gui:
  theme:
    activeBorderColor:
      - '#b85a3a'
      - bold
    inactiveBorderColor:
      - '#444444'
    optionsTextColor:
      - '#b85a3a'
    selectedLineBgColor:
      - '#2a2a4e'
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitBgColor:
      - '#ffaa00'
    cherryPickedCommitFgColor:
      - '#ffffff'
    markedBaseCommitFgColor:
      - '#b85a3a'
    markedBaseCommitBgColor:
      - '#2a2a4e'
    unstagedChangesColor:
      - '#ff4444'
    defaultFgColor:
      - '#c0c0c0'
    searchingActiveBorderColor:
      - '#ff0088'
      - bold
  skipDiscardChangeWarning: false

authorColors:
  '*': '#b4befe'

os:
  editor: true
