customCommands:
  - key: ';'
    context: 'global'
    command: '/home/armaghan/.lazygit-commit.sh'
    output: terminal
    description: 'Quick add, commit, push'

gui:
  theme:
    activeBorderColor:
      - '#00ffff'
      - bold
    inactiveBorderColor:
      - '#0080ff'
    searchingActiveBorderColor:
      - '#ff00ff'
      - bold
    optionsTextColor:
      - '#00ff00'
    selectedLineBgColor:
      - '#000000'
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - '#ffff00'
    cherryPickedCommitBgColor:
      - '#ff0080'
    markedBaseCommitFgColor:
      - '#00ffff'
    markedBaseCommitBgColor:
      - '#8000ff'
    unstagedChangesColor:
      - '#ff0000'
    defaultFgColor:
      - '#ffffff'
  skipDiscardChangeWarning: false
  authorColors:
    '*': '#7287fd'

os:
  editor: true
