customCommands:
  - key: ';'
    context: 'global'
    command: '/home/armaghan/.lazygit-commit.sh'
    output: terminal
    description: 'Quick add, commit, push'

gui:
  theme:
    activeBorderColor:
      - '#88c0d0'
      - bold
    inactiveBorderColor:
      - '#4c566a'
    optionsTextColor:
      - '#a3be8c'
    selectedLineBgColor:
      - '#3b4252'
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitBgColor:
      - '#d08770'
    cherryPickedCommitFgColor:
      - '#ebcb8b'
    markedBaseCommitFgColor:
      - '#81a1c1'
    markedBaseCommitBgColor:
      - '#b48ead'
    unstagedChangesColor:
      - '#bf616a'
    defaultFgColor:
      - '#eceff4'
    searchingActiveBorderColor:
      - '#bf616a'
      - bold
  skipDiscardChangeWarning: false

authorColors:
  '*': '#b4befe'

os:
  editor: true
