return {
	ensure_installed = {
		"lua-language-server",
		"gopls",
		"pyright",
		"bash-language-server",
		"css-lsp",
		"tailwindcss-language-server",
		"clangd",
		"json-lsp",
		"typescript-language-server",
		"emmet-ls",
		"sqls",
		"marksman",
		"svelte-language-server",
		"asm-lsp",
		"markdown-oxide",
		"html-lsp",
		"lemminx",
		"vue-language-server",
		"stylua",
		"black",
		"isort",
		"mypy",
		"clang-format",
		"sqlfmt",
		"gofumpt",
		"goimports-reviser",
		"golines",
		"ruff",
		"eslintd",
		"prettierd",
		"shfmt",
	},
	PATH = "skip",
	ui = {
		icons = {
			package_pending = " ",
			package_installed = "󰄳 ",
			package_uninstalled = " 󰚌",
		},
		keymaps = {
			toggle_server_expand = "<CR>",
			install_server = "i",
			update_server = "u",
			check_server_version = "c",
			update_all_servers = "U",
			check_outdated_servers = "C",
			uninstall_server = "X",
			cancel_installation = "<C-c>",
		},
	},
	max_concurrent_installers = 10,
}
