return {
  ensure_installed = {
    -- LSP Servers
    "lua-language-server",
    "gopls",
    "pyright",
    "bash-language-server",
    "css-lsp",
    "tailwindcss-language-server",
    "clangd",
    "json-lsp",
    "typescript-language-server",
    "emmet-ls",
    "sqls",
    "marksman",
    "svelte-language-server",
    "asm-lsp",
    "markdown-oxide",
    -- Formatters & Linters
    "stylua",
    "black",
    "mypy",
    "clang-format",
    "sqlfmt",
    "gofumpt",
    "goimports-reviser",
    "golines",
    "ruff",
    "eslintd",
    "prettierd",
  },
}
